apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260609-135116-h58v7ok33emc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260609-135116-h58v7ok33emc.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260609-135116-h58v7ok33emc-service
            port:
              number: 80
